name: "Where-Ya-At Bulb"
slug: where_ya_at_bulb
description: "Ingress UI to generate Home Assistant packages for a location-driven lighting mode system"
version: "0.1.2"
url: "https://github.com/CJStev1985/Where-Ya-At-Bulb"
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
  - i386
startup: services
init: false
ingress: true
ingress_port: 8099
panel_title: "Where-Ya-At Bulb"
panel_icon: "mdi:lightbulb-auto"
map:
  - config:rw
options:
  package_path: "packages/where_ya_at_bulb_generated.yaml"
  location_mode_entity: "input_select.location_mode"
  manual_override_entity: "input_boolean.light_manual_override"
  dwell_seconds: 300
schema:
  package_path: str
  location_mode_entity: str
  manual_override_entity: str
  dwell_seconds: int(30,3600)
